version: '3'

services:

  nginx:
    image: nginx:1.17.4-alpine
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - 80:80

  php:
    build: ./docker/php
    restart: always
    volumes:
      - ./app:/var/www/html
    expose: 
      - 9000

  node:
    image: node:8.16.1-alpine
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    command: sh -c 'npm install'

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: gfapp
      POSTGRES_USER: gfapp
      POSTGRES_PASSWORD: secrpass
    ports:
      - 5432:5432

  pgadmin:
    image: dockage/phppgadmin
    depends_on:
      - db
    ports:
      - 8080:80  
