version: '3'

services:

  nginx:
    image: nginx:1.17.4-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    expose: 
      - 9000
