version: '3'

services:

  nginx:
    image: nginx:1.17.4-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - 80:80

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    expose: 
      - 9000

  node:
    image: node:8.16.1-alpine
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    expose: 
      - 9000
    command: sh -c 'npm install'
