version: '3.1'

services:

  nginx:
    image: nginx:1.17.4-alpine
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - ${NGINX_PORT}:80

  php:
    build: ./docker/php
    build: 
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    restart: always
    volumes:
      - ./app:/var/www/html
    expose: 
      - 9000
    command: bash -c "composer install && php artisan migrate"

  node:
    image: node:8.16.1-alpine
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    command: sh -c 'npm install'

  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_DB: gfapp
      POSTGRES_USER: gfapp
      POSTGRES_PASSWORD: secrpass
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.4
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
